version: 0.5.{build}.0

configuration: Release

platform: Any CPU

assembly_info:
  patch: true
  file: GraveRobber\Properties\AssemblyInfo.cs
  assembly_version: '0.5.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '0.5.0-beta'

before_build:
- nuget restore

build:
  project: GraveRobber.sln
  parallel: true
  verbosity: minimal
